<a href="https://colab.research.google.com/github/SiddheshP2709/my_DCCproject/blob/main/pdfToCsv.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install tabula-py

Collecting tabula-py
  Downloading tabula_py-2.9.0-py3-none-any.whl (12.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.0/12.0 MB 24.8 MB/s eta 0:00:00
Requirement already satisfied: pandas>=0.25.3 in /usr/local/lib/python3.10/dist-packages (from tabula-py) (2.0.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from tabula-py) (1.25.2)
Requirement already satisfied: distro in /usr/lib/python3/dist-packages (from tabula-py) (1.7.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2023.4)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.25.3->tabula-py) (2024.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas>=0.25.3->tabula-py) (1.16.0)
Installing collected packages: tabula-py
Successfully installed tabula-py-2.9.0

In [ ]:
import tabula
import pandas as pd
import csv

In [ ]:
pdf_path = "elec1.pdf"
tables = tabula.read_pdf(pdf_path, pages='all', multiple_tables=True)

concatenated_df = pd.concat(tables, ignore_index=True)
concatenated_df = concatenated_df.astype(str)
concatenated_df.to_csv("electoral1.csv", index=False)
print("Combined table saved as CSV.")

Combined table saved as CSV.

In [ ]:
electoral1 = pd.read_csv('electoral1.csv')
display(electoral1)

,Sr No.,Date of Encashment,Name of the Political Party,Account no. of Political Party,Prefix,Bond Number,Denominations,Pay Branch Code,Pay Teller
0,1,12/Apr/2019,ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM,*******5199,OC,775,"1,00,00,000",800,2770121
1,2,12/Apr/2019,ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM,*******5199,OC,3975,"1,00,00,000",800,2770121
2,3,12/Apr/2019,ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM,*******5199,OC,3967,"1,00,00,000",800,2770121
3,4,12/Apr/2019,ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM,*******5199,TL,10418,"10,00,000",800,2770121
4,5,12/Apr/2019,ALL INDIA ANNA DRAVIDA MUNNETRA KAZHAGAM,*******5199,TL,126,"10,00,000",800,2770121
...,...,...,...,...,...,...,...,...,...
20416,20417,24/Jan/2024,JANASENA PARTY,*******3929,TL,2619,"10,00,000",847,7620160
20417,20418,24/Jan/2024,JANASENA PARTY,*******3929,TL,2608,"10,00,000",847,7620160
20418,20419,24/Jan/2024,JANASENA PARTY,*******3929,TL,2633,"10,00,000",847,7620160
20419,20420,24/Jan/2024,JANASENA PARTY,*******3929,TL,2627,"10,00,000",847,7620160
20420,20421,24/Jan/2024,JANASENA PARTY,*******3929,TL,2631,"10,00,000",847,7620160

In [ ]:
pdf_path = "elec2.pdf"
tables = tabula.read_pdf(pdf_path, pages='all', multiple_tables=True)

concatenated_df = pd.concat(tables, ignore_index=True)
concatenated_df = concatenated_df.astype(str)
concatenated_df.to_csv("electoral2.csv", index=False)
print("Combined table saved as CSV.")

Combined table saved as CSV.

In [ ]:
ds = pd.read_csv('electoral2.csv')
display(ds)

,Sr No.,Reference No (URN),Journal Date,Date of Purchase,Date of Expiry,Name of the Purchaser,Prefix,Bond Number,Denominations,Issue Branch Code,Issue Teller,Status
0,1,00001201904120000001166,12/Apr/2019,12/Apr/2019,26/Apr/2019,A B C INDIA LIMITED,TL,11448,"10,00,000",1,5899230,Paid
1,2,00001201904120000001166,12/Apr/2019,12/Apr/2019,26/Apr/2019,A B C INDIA LIMITED,TL,11447,"10,00,000",1,5899230,Paid
2,3,00001201904120000001166,12/Apr/2019,12/Apr/2019,26/Apr/2019,A B C INDIA LIMITED,TL,11441,"10,00,000",1,5899230,Paid
3,4,00001201904120000001166,12/Apr/2019,12/Apr/2019,26/Apr/2019,A B C INDIA LIMITED,OL,1113,"1,00,000",1,5899230,Paid
4,5,00001201904120000001166,12/Apr/2019,12/Apr/2019,26/Apr/2019,A B C INDIA LIMITED,OL,1118,"1,00,000",1,5899230,Paid
...,...,...,...,...,...,...,...,...,...,...,...,...
18866,18867,1202401110000003729,11/Jan/2024,11/Jan/2024,25/Jan/2024,WESTWELL GASES PRIVATE LIMITED,OC,15695,"1,00,00,000",1,5898161,Paid
18867,18868,1202401110000003729,11/Jan/2024,11/Jan/2024,25/Jan/2024,WESTWELL GASES PRIVATE LIMITED,OC,15693,"1,00,00,000",1,5898161,Paid
18868,18869,1202401110000003729,11/Jan/2024,11/Jan/2024,25/Jan/2024,WESTWELL GASES PRIVATE LIMITED,OC,15697,"1,00,00,000",1,5898161,Paid
18869,18870,1202401110000003729,11/Jan/2024,11/Jan/2024,25/Jan/2024,WESTWELL GASES PRIVATE LIMITED,OC,17803,"1,00,00,000",1,5898161,Paid
18870,18871,1202401110000003729,11/Jan/2024,11/Jan/2024,25/Jan/2024,WESTWELL GASES PRIVATE LIMITED,OC,15691,"1,00,00,000",1,5898161,Paid